#!/bin/bash
# 16.04
sudo apt-get update
sudo apt-get install -y curl php-cli php-mbstring git unzip
cd ~
curl -sS https://getcomposer.org/installer -o composer-setup.php
sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer

# more info: http://www.cyberciti.biz/faq/how-to-install-composer-on-debian-ubuntu-linux-server/
